[colors.primary]
background = '#0a151a'
foreground = '#d9e4eb'
 
[colors.cursor]
text = '#d9e4eb'
cursor = '#b4cad6' 
 
[colors.vi_mode_cursor]
text = '#0a151a'
cursor = '#59dbc0' 
 
[colors.search.matches]
foreground = '#354a54' 
background = '#8ccff0' 
 
[colors.search.focused_match]
foreground = '#354a54' 
background = '#59dbc0' 
 
[colors.footer_bar]
foreground = '#354a54' 
background = '#d9e4eb' 
 
[colors.hints.start]
foreground = '#354a54' 
background = '#84d6c2' 
 
[colors.hints.end]
foreground = '#354a54' 
background = '#84d6c2' 
 
[colors.selection]
text = '#0a151a'
background = '#59dbc0'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#59dbc0' 
yellow = '#006b5b' 
blue = '#59dbc0' 
magenta = '#8ccff0' 
cyan = '#84d6c2' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 